version: '3.8'

name: TBJR-dev

networks:
  network:
    driver: bridge

services:
  app:
    container_name: app-dev
    depends_on:
      - db
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env.dev
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - BOT_TOKEN=${BOT_TOKEN}
    networks:
      - network

  db:
    container_name: db-dev
    image: postgres
    restart: unless-stopped
    env_file:
      - .env.dev
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: tbjr_db_data