spring:
  application:
    name: "Telegram bot Java Rush"

  datasource:
    url: jdbc:postgresql://localhost:5433/tbjr
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

bot:
  token: "8369059576:AAG0zzeJk9ifIDY31iKD40h8MxtYC0fBCYw"
  recountNewArticleFixedRate: 900000

javarush:
  api:
    path: https://javarush.com/api/1.0/rest
