spring:
  application:
    name: "Telegram bot Java Rush"

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

bot:
  token: ${BOT_TOKEN}
  recountNewPostFixedRate: 900000
  admins: ${BOT_ADMINS}

javarush:
  api:
    path: https://javarush.com/api/1.0/rest

